import { JobListing } from "@/types";

function generateUUID(): string {
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function (c) {
    const r = Math.random() * 16 | 0, v = c === 'x' ? r : (r & 0x3 | 0x8);
    return v.toString(16);
  });
}

export const suggestedJobs: JobListing[] = [
  {
    id: generateUUID(),
    title: "Customer Service Representative",
    caption: "Looking for a friendly and driven Customer Representative to join our growing team! If you're passionate about helping people and have excellent... See more",
    company: "The Uprise",
    location: "Davao City",
    date: new Date("2024-03-01"),
    isApplied: false,
    poster: "Randy Acabado",
    posterImg: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=1964&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG0dby1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    color: "orange",
  },
  {
    id: generateUUID(),
    title: "Software Engineer (Backend)",
    caption: "Join our team of talented engineers to build scalable and robust backend systems. Experience with Node.js and Python is a plus... See more",
    company: "Tech Innovators",
    location: "Manila",
    date: new Date("2024-04-15"),
    isApplied: false,
    poster: "Sarah Lim",
    posterImg: "https://images.unsplash.com/photo-1573496799652-408c2ac9b80b?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG0dby1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    color: "orange",
  },
  {
    id: generateUUID(),
    title: "Data Analyst",
    caption: "Analyze large datasets and provide insights to drive business decisions. Strong SQL and data visualization skills required... See more",
    company: "Data Dynamics",
    location: "Cebu City",
    date: new Date("2024-05-01"),
    isApplied: false,
    poster: "Miguel Reyes",
    posterImg: "https://images.unsplash.com/photo-1589561865912-cedc9b74b71c?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG0dby1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    color: "orange",
  },
  {
    id: generateUUID(),
    title: "Marketing Specialist",
    caption: "Develop and execute marketing campaigns to increase brand awareness and drive sales. Experience with digital marketing is essential... See more",
    company: "Market Maven",
    location: "Quezon City",
    date: new Date("2024-06-15"),
    isApplied: false,
    poster: "Anna Cruz",
    posterImg: "https://images.unsplash.com/photo-1559526373-c5f943558226?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG0dby1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    color: "orange",
  },
  {
    id: generateUUID(),
    title: "UI/UX Designer",
    caption: "Create intuitive and visually appealing user interfaces for our web and mobile applications. Portfolio showcasing your design skills is required... See more",
    company: "Design Hub",
    location: "Iloilo City",
    date: new Date("2024-07-01"),
    isApplied: false,
    poster: "Joshua Santos",
    posterImg: "https://images.unsplash.com/photo-1588681664899-f142a6775e59?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG0dby1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    color: "orange",
  },
  {
    id: generateUUID(),
    title: "Project Manager",
    caption: "Lead and manage projects from initiation to completion, ensuring timely delivery and adherence to budget. Strong organizational and communication skills required... See more",
    company: "Project Pros",
    location: "Baguio City",
    date: new Date("2024-08-15"),
    isApplied: false,
    poster: "Maria Garcia",
    posterImg: "https://images.unsplash.com/photo-1530268729831-4b0b9e170218?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG0dby1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    color: "orange",
  },
  {
    id: generateUUID(),
    title: "Network Administrator",
    caption: "Maintain and optimize network infrastructure, ensuring smooth and secure operations. Experience in network security and troubleshooting is essential... See more",
    company: "Net Secure",
    location: "General Santos City",
    date: new Date("2024-09-01"),
    isApplied: false,
    poster: "Carlos Dela Cruz",
    posterImg: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG0dby1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    color: "orange",
  },
  {
    id: generateUUID(),
    title: "Sales Representative",
    caption: "Drive sales and build strong customer relationships. Excellent communication and negotiation skills are a must... See more",
    company: "Sales Force",
    location: "Tacloban City",
    date: new Date("2024-10-15"),
    isApplied: false,
    poster: "Elena Torres",
    posterImg: "https://images.unsplash.com/photo-1552664730-d307ca884978?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG0dby1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    color: "orange",
  },
  {
    id: generateUUID(),
    title: "Human Resources Specialist",
    caption: "Manage recruitment, onboarding, and employee relations. Knowledge of labor laws and HR best practices is required... See more",
    company: "HR Solutions",
    location: "Zamboanga City",
    date: new Date("2024-11-01"),
    isApplied: false,
    poster: "Ricardo Fernandez",
    posterImg: "https://images.unsplash.com/photo-1542744166-e159386539bc?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG0dby1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    color: "orange",
  },
  {
    id: generateUUID(),
    title: "Financial Analyst",
    caption: "Analyze financial data and provide insights to support business decisions. Strong analytical and financial modeling skills are required... See more",
    company: "Finance First",
    location: "Batangas City",
    date: new Date("2024-12-15"),
    isApplied: false,
    poster: "Isabel Navarro",
    posterImg: "https://images.unsplash.com/photo-1556761175-4c633a9586e8?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG0dby1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    color: "orange",
  },
];
